services:
  mihoyo-bbs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miHoYo-BBS-Tools
    restart: always
    environment:
      - CRON_SIGNIN=30 9 * * *
      - MULTI=TRUE
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
